spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#    # 테이블 생성 후에 data.sql 실행
#    defer-datasource-initialization: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test
      username: sa
      idle-timeout: 600000
      minimum-idle: 2
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: false
  thymeleaf:
    cache: false


server:
  port: 80